version: "3"
services:
  grpc-service:
    build:
      context: $BLOGBACKENDPATH/grpc-service/
      dockerfile: $BLOGBACKENDPATH/grpc-service/Dockerfile
    ports:
      - "10000:10000"
    expose:
      - "10000"
  grpc-gateway:
    depends_on:
      - grpc-service
    build:
      context: $BLOGBACKENDPATH/grpc-gateway/
      dockerfile: $BLOGBACKENDPATH/grpc-gateway/Dockerfile
    ports:
      - "8080:8080"
    expose:
      - "8080"
    links:
      - "grpc-service:service"
  blog-frontend:
    container_name: blog-frontend
    build:
      context: $BLOGFRONTENDPATH/
      dockerfile: $BLOGFRONTENDPATH/Dockerfile
    ports:
      - '80:80'